#!/bin/bash

export INSTALL_DIR="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <your-service-file-name>" >&2
  exit 1
fi

unit=$1
unit_blue=octoblu-$unit-blue@.service
unit_green=octoblu-$unit-green@.service
unit_green_healthcheck=octoblu-$unit-green-healthcheck.service
unit_blue_healthcheck=octoblu-$unit-blue-healthcheck.service
unit_green_register=octoblu-$unit-green-register@.service
unit_blue_register=octoblu-$unit-blue-register@.service

printf "unit:> %s  \n" $unit

printf "destroying:> %s\n" $unit_blue
fleetctl destroy $unit_blue

printf "destroying:> %s\n" $unit_green
fleetctl destroy $unit_green

printf "destroying:> %s\n" $unit_blue_healthcheck
fleetctl destroy $unit_blue_healthcheck

printf "destroying:> %s\n" $unit_green_healthcheck
fleetctl destroy $unit_green_healthcheck

printf "destroying:> %s\n" $unit_blue_register
fleetctl destroy $unit_blue_register

printf "destroying:> %s\n" $unit_green_register
fleetctl destroy $unit_green_register

printf "submitting:> %s \n" $unit_blue
fleetctl submit $INSTALL_DIR/services.d/$unit/$unit_blue

printf "submitting:> %s \n" $unit_green
fleetctl submit $INSTALL_DIR/services.d/$unit/$unit_green

printf "submitting:> %s \n" $unit_blue_healthcheck
fleetctl submit $INSTALL_DIR/services.d/$unit/$unit_blue_healthcheck

printf "submitting:> %s \n" $unit_green_healthcheck
fleetctl submit $INSTALL_DIR/services.d/$unit/$unit_green_healthcheck

printf "submitting:> %s \n" $unit_blue_register
fleetctl submit $INSTALL_DIR/services.d/$unit/$unit_blue_register

printf "submitting:> %s \n" $unit_green_register
fleetctl submit $INSTALL_DIR/services.d/$unit/$unit_green_register

printf "listing units:> \n"
fleetctl list-units | grep $unit

printf "done:> %s\n" $unit
