#!/bin/bash

export INSTALL_DIR="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
REMOTE_SERVER=$1

if [ -z "$REMOTE_SERVER" ]; then
  echo "Usage: ./push-production-config <REMOTE_SERVER>"
  exit 1
fi

COMMAND="echo 'updating etcd'"
ETCD_PAIRS=$(cat $INSTALL_DIR/production-config.d/*)
while read -r ETCD_PAIR; do
  PAIR=($ETCD_PAIR)
  KEY=${PAIR[0]}
  VALUE=${PAIR[1]}

  COMMAND="${COMMAND} && etcdctl set ${KEY} ${VALUE} > /dev/null"
done <<< "$ETCD_PAIRS"

echo $COMMAND

ssh "core@${REMOTE_SERVER}" $COMMAND
