#!/bin/bash

add_quay_hook() {
  local project_name="$1"

  quayhook "${project_name}"
}

generate_service_files() {
  local project_name="$1"
  local directory="$2"

  deployinate-configurator traefik \
    --dir "${directory}" \
    "${project_name}"
}

remove_old_service_files() {
  local project_name="$1"
  local directory="$2"

  git -C "${directory}" rm -f \
    "octoblu-${project_name}-blue*.service" \
    "octoblu-${project_name}-green*.service"
}

update_service_files() {
  local project_name="$1"
  local directory="${HOME}/Projects/Octoblu/the-stack-services/services.d/${project_name}"

  generate_service_files "${project_name}" "${directory}" \
    && remove_old_service_files "${project_name}" "${directory}"
}

update_minord(){
  local project_name="$1"
  local git_directory="${HOME}/Projects/Octoblu/the-stack-services/services.d/${project_name}"
  local minor_directory="${HOME}/Projects/Octoblu/the-stack-env-production/minor/etcd/octoblu/${project_name}"
  local major_directory="${HOME}/Projects/Octoblu/the-stack-env-production/major/etcd/octoblu/${project_name}"

  cp -r "${major_directory}" "${minor_directory}"
  rm -r \
    "${minor_directory}/blue" \
    "${minor_directory}/green" \
    "${minor_directory}/host" \
    "${minor_directory}/target" \
    "${minor_directory}/active" \
    "${minor_directory}/current_step" \
    "${minor_directory}/count"

  minorsync load "${project_name}"
}

update_vulcand(){
  local project_name="$1"
  local host="$2"
  local vulcand_dir="${HOME}/Projects/Octoblu/the-stack-env-production/major/vulcand/"

  local script_dir=$(dirname "${BASH_SOURCE[0]}")
  bash -c "${script_dir}/build-vulcand \"${vulcand_dir}\" \"octoblu-${project_name}\" \"${host}\""
}


main(){
  local project_name="$1"
  local host="$2"

  if [ -z "${project_name}" -o -z "${host}" ]; then
    echo "Requires project_name, host. Got: '${project_name}', '${host}'"
  fi

  echo "Migrating ${project_name} with host ${host}, you've got 5 seconds to cancel (ctrl+c)"
  sleep 5

  echo "Too late" \
    && update_service_files "${project_name}" \
    && update_minord "${project_name}" \
    && update_vulcand "${project_name}" "${host}" \
    && add_quay_hook "${project_name}"

  echo ""
  echo "Things you still need to do:"
  echo "  * remove Quay's old webhook"
  echo "  * deploy a version"
  echo "  * submit, load, and start the services"
  echo "  * run 'vulcansync ${project_name}'"
}
main $@
