#!/bin/bash

generate_service_files(){
  echo "generate_service_files"
  local project_name="$1"
  local service_type="$2"
  local directory_name="${HOME}/Projects/Octoblu/the-stack-services/services.d/${project_name}"

  deployinate-configurator "${service_type}" \
    --dir "${directory_name}" \
    "${project_name}"
}

major_fleetctl(){
  env \
    FLEETCTL_TUNNEL=52.32.210.244 \
    fleetctl --strict-host-key-checking=false $@
}

major_units(){
  local project_name="$1"
  local directory_name="${HOME}/Projects/Octoblu/the-stack-services/services.d/${project_name}"
  local unit_count=0
  local templates=""

  unit_count="$(major_fleetctl list-units --no-legend \
    | grep "octoblu-${project_name}@" \
    | wc -l)"

  if [ "${unit_count}" == "0" ]; then
    return 0
  fi

  pushd "${directory_name}" > /dev/null
  templates=(*)
  popd > /dev/null
  templates=( $(printf "%s\n" ${templates[@]} | sort -r) )
  for num in $(seq 1 "${unit_count}"); do
    for template in "${templates[@]}"; do
      local name="$(echo $template | sed 's/\.service//g')"
      echo -n "${name}${num} "
    done
  done
}

minor_fleetctl(){
  env \
    FLEETCTL_TUNNEL=52.89.122.251 \
    fleetctl --strict-host-key-checking=false $@
}

minor_units(){
  local project_name="$1"
  local directory_name="${HOME}/Projects/Octoblu/the-stack-services/services.d/${project_name}"
  local unit_count=0
  local templates=""

  unit_count="$(minor_fleetctl list-units --no-legend \
    | grep "octoblu-${project_name}@" \
    | wc -l)"

  if [ "${unit_count}" == "0" ]; then
    return 0
  fi

  pushd "${directory_name}" > /dev/null
  templates=(*)
  popd > /dev/null
  templates=( $(printf "%s\n" ${templates[@]} | sort -r) )
  for num in $(seq 1 "${unit_count}"); do
    for template in "${templates[@]}"; do
      local name="$(echo $template | sed 's/\.service//g')"
      echo -n "${name}${num} "
    done
  done
}

push_to_major(){
  echo "push_to_major"
  local project_name="$1"
  local directory_name="${HOME}/Projects/Octoblu/the-stack-services/services.d/${project_name}"

  pushd "${directory_name}"
  major_fleetctl destroy *
  major_fleetctl submit *
  sleep 1
  major_fleetctl submit *
  popd
}

push_to_minor(){
  echo "push_to_minor"
  local project_name="$1"
  local directory_name="${HOME}/Projects/Octoblu/the-stack-services/services.d/${project_name}"

  pushd "${directory_name}"
  minor_fleetctl destroy *
  minor_fleetctl submit *
  sleep 1
  minor_fleetctl submit *
  popd
}

restart_majors(){
  echo "restart_majors"
  local project_name="$1"
  local units=( $(major_units "${project_name}") )

  for unit in "${units[@]}"; do
    local check_status=1
    local status_indicator='='
    echo "restart '${unit}'"
    major_fleetctl destroy "${unit}"
    sleep 2
    major_fleetctl load "${unit}"
    while [ "${check_status}" == "1" ]; do
      echo "${status_indicator} start '${unit}'"
      major_fleetctl start "${unit}"
      sleep 2

      major_fleetctl list-units | grep "${unit}" | grep running
      check_status=$?
      status_indicator="${status_indicator}="
    done
  done
  return 0
}

restart_minors(){
  echo "restart_minors"
  local project_name="$1"
  local units=( $(minor_units "${project_name}") )

  for unit in "${units[@]}"; do
    local check_status=1
    local status_indicator='='
    echo "restart '${unit}'"
    minor_fleetctl destroy "${unit}"
    sleep 2
    minor_fleetctl load "${unit}"
    while [ "${check_status}" == "1" ]; do
      echo "${status_indicator} start '${unit}'"
      minor_fleetctl start "${unit}"
      sleep 2

      minor_fleetctl list-units | grep "${unit}" | grep running
      check_status="$?"
      status_indicator="${status_indicator}="
    done
  done
  return 0
}

main(){
  local project_name="$1"
  local service_type="${2:-service}"

  generate_service_files "${project_name}" "${service_type}" \
  && push_to_minor "${project_name}" \
  && restart_minors "${project_name}" \
  && sleep 30 \
  && push_to_major "${project_name}" \
  && restart_majors "${project_name}"
  local exit_code=$?
  exit ${exit_code}
}
main $@
